import type { Account, Transaction } from "./finance";

export const INITIAL_ACCOUNTS: Account[] = [
	{
		id: "acc-nubank",
		name: "Nubank (Conta Principal)",
		type: "checking",
		balance: 4580.3,
		color: "#8b5cf6",
	},
	{
		id: "acc-itau",
		name: "Itaú Uniclass",
		type: "checking",
		balance: 1240.0,
		color: "#f97316",
	},
	{
		id: "acc-cartao-black",
		name: "Cartão Ultravioleta",
		type: "credit_card",
		balance: -2150.4,
		color: "#0d0d0d",
		closingDay: 28,
		dueDay: 5,
		creditLimit: 15000,
	},
	{
		id: "acc-xp",
		name: "XP Investimentos",
		type: "investment",
		balance: 32500.0,
		color: "#0fa76e",
	},
];

export const CATEGORY_COLORS: Record<
	string,
	{ bg: string; text: string; fill: string }
> = {
	"Alimentação & Mercado": {
		bg: "bg-emerald-50",
		text: "text-emerald-700",
		fill: "#18E299",
	},
	"Moradia & Contas": {
		bg: "bg-blue-50",
		text: "text-blue-700",
		fill: "#3772cf",
	},
	"Transporte & Mobilidade": {
		bg: "bg-amber-50",
		text: "text-amber-700",
		fill: "#c37d0d",
	},
	"Lazer & Entretenimento": {
		bg: "bg-purple-50",
		text: "text-purple-700",
		fill: "#8b5cf6",
	},
	"Saúde & Bem-estar": {
		bg: "bg-rose-50",
		text: "text-rose-700",
		fill: "#d45656",
	},
	"Educação & Livros": {
		bg: "bg-cyan-50",
		text: "text-cyan-700",
		fill: "#06b6d4",
	},
	"Assinaturas & Software": {
		bg: "bg-indigo-50",
		text: "text-indigo-700",
		fill: "#6366f1",
	},
	Investimentos: { bg: "bg-teal-50", text: "text-teal-700", fill: "#0fa76e" },
	"Salário & Faturamento": {
		bg: "bg-emerald-100",
		text: "text-emerald-800",
		fill: "#10b981",
	},
	Outros: { bg: "bg-stone-50", text: "text-stone-700", fill: "#78716c" },
};

export const INITIAL_TRANSACTIONS: Transaction[] = [
	{
		id: "tx-1",
		description: "Supermercado Mensal Pão de Açúcar",
		amount: 1240.5,
		type: "expense",
		category: "Alimentação & Mercado",
		date: "2026-09-14",
		paymentMethod: "Cartão de Crédito",
		accountId: "acc-cartao-black",
		tags: ["Mercado", "Essencial"],
		status: "completed",
	},
	{
		id: "tx-2",
		description: "Aluguel & Condomínio Edifício Jardins",
		amount: 2850.0,
		type: "expense",
		category: "Moradia & Contas",
		date: "2026-09-05",
		paymentMethod: "PIX",
		accountId: "acc-nubank",
		tags: ["Fixo", "Moradia"],
		status: "completed",
	},
	{
		id: "tx-3",
		description: "Gasolina Posto Shell",
		amount: 320.0,
		type: "expense",
		category: "Transporte & Mobilidade",
		date: "2026-09-12",
		paymentMethod: "Débito",
		accountId: "acc-nubank",
		tags: ["Transporte"],
		status: "completed",
	},
	{
		id: "tx-4",
		description: "Jantar Especial Bistrô",
		amount: 215.0,
		type: "expense",
		category: "Lazer & Entretenimento",
		date: "2026-09-13",
		paymentMethod: "Cartão de Crédito",
		accountId: "acc-cartao-black",
		tags: ["Lazer"],
		status: "completed",
	},
	{
		id: "tx-5",
		description: "Plano de Saúde Bradesco",
		amount: 480.0,
		type: "expense",
		category: "Saúde & Bem-estar",
		date: "2026-09-02",
		paymentMethod: "Boleto",
		accountId: "acc-itau",
		tags: ["Saúde", "Fixo"],
		status: "completed",
	},
	{
		id: "tx-6",
		description: "Assinaturas Vercel + OpenAI + GitHub",
		amount: 149.9,
		type: "expense",
		category: "Assinaturas & Software",
		date: "2026-09-10",
		paymentMethod: "Cartão de Crédito",
		accountId: "acc-cartao-black",
		tags: ["Dev", "Trabalho"],
		status: "completed",
	},
	{
		id: "tx-7",
		description: "Aporte Tesouro Selic 2029",
		amount: 1500.0,
		type: "expense",
		category: "Investimentos",
		date: "2026-09-08",
		paymentMethod: "PIX",
		accountId: "acc-nubank",
		tags: ["Investimentos", "Patrimônio"],
		status: "completed",
	},
	{
		id: "tx-8",
		description: "Salário & Faturamento Consultoria",
		amount: 10500.0,
		type: "income",
		category: "Salário & Faturamento",
		date: "2026-09-05",
		paymentMethod: "PIX",
		accountId: "acc-nubank",
		tags: ["Renda Principal"],
		status: "completed",
	},
];
